### ISSUE TITLE
Issue installing katuali

### ISSUE THREAD

**Issue by xyloforce** [nanoporetech/katuali#5]
Hello,
I've been trying to install katuali on my university server (running debian) and when I do "make install" I get the following error :
```
OSError: Command /data/home/fsassolas/katuali/venv/bin/python3 - setuptools pkg_resources pip wheel failed with error code 1
make: *** [Makefile:17: venv/bin/activate] Error 1
```
How may I solve the issue ?

**Comment by javierblasco** [comment]
Hi @xyloforce, 

The rule of the Makefile that is failing is `venv/bin/activate`, which creates the virtualenv and uses pip to install requirements. The fact the error mentions the python3 within `venv` would seem to indicate the creation has succeeded, so I imagine your problem is with `pip`. Could you run `pip --version` to have an idea if `pip` is installed, and what version?

**Comment by xyloforce** [comment]
python-pip isn't installed so when I try the command I get an error :
```
~$ pip --version
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
```
If I try to call it with python I get the following versions :
```
~$ python -m pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg (python 2.7)
~$ python3 -m pip --version
pip 19.3.1 from /data/home/fsassolas/.local/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by javierblasco** [comment]
Hi @xyloforce, the `TypeError` indicates pip is actually installed, and you are hitting [a known problem](https://github.com/pypa/pip/issues/7205#issuecomment-541926212). I think you have two options: 

1) Get those in charge of the university server to help you reinstall pip
2) Modify line 18 of the Makefile to `${IN_VENV} && python3 -m pip install pip --upgrade`

After that, I believe the subsequent `pip` commands will work, because you will be using the installation within your venv, but if that is not the case, you will need to substitute again once in lines 19, 28 and 95. 

Of course, if this does not work, let us know and we will try alternatives

**Comment by xyloforce** [comment]
I tried (2) and I got the same error (AttributeError: module 'pip' has no attribute 'main'). As I'm not sure if I typed the line correctly, here is the modified Makefile (.txt so Github let me upload it)
[Makefile.txt](https://github.com/nanoporetech/katuali/files/3855609/Makefile.txt)
We tried with another bioinformatician to fix the issue and the trouble started with the preceding line (`test -d venv || virtualenv venv --prompt '(katuali) ' --python=python3`) : in a empty directory we got the exact same error so isn't there an issue in virtualenv as well ?

**Comment by javierblasco** [comment]
Hi @xyloforce. In that case, your best option is probably to download and install pip within your `./local` (or other) using the bootstrap pip installer. Complete instructions can be found [in the pypa webpage](https://pip.pypa.io/en/stable/installing/).

**Comment by xyloforce** [comment]
Hi !
So I've successfully installed pip with `get-pip.py` but the system keeps using the broken one in `/usr/local` ? How can I force him to use the `~/.local/bin` one instead ?
Many thanks for your help :)

**Comment by javierblasco** [comment]
Hi @xyloforce,

Please, keep in mind this is slightly out of my area of expertise, but I'd think that you need to set your `~/.local/bin` earlier than `/usr/local` in your `$PATH` variable. It should suffice with doing:

`export PATH=~/.local/bin:$PATH`

This will work for as long as the terminal is open. For it to be permanent the same line can be added to your `~/.bashrc` or `~/.bash_profile` file.

**Comment by mwykes** [comment]
Hi @xyloforce, is this issue now resolved?
